services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword123
      - MYSQL_DATABASE=walletly
      - MYSQL_USER=user
      - MYSQL_PASSWORD=userpassword123
    volumes:
      - "./app/db:/docker-entrypoint-initdb.d"
      - mysql_data:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - app-network


  www:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - "./:/usr/src/Walletly"
      - /usr/src/Walletly/node_modules
    ports:
      - "8080:3000"
    networks:
      - app-network
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=userpassword123
      - DB_NAME=walletly
      - DB_PORT=3306
      - PORT=3000

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8001:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=rootpassword123
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
    name: my_project_mysql_data